### ISSUE TITLE
when i load page in mobile. video is not autoplay.

### ISSUE THREAD

**Issue by winditprog** [mkay581/youtube-video-js#10]
message from developed console : Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.

this is my code: 

var videoEl = document.getElementById("slider-bg-video");

    var player = new YoutubeVideo({
        el: videoEl,
        customWrapperClass : "video-wrapper flex-video widescreen"
    });
    videoEl.load().then(function () {
        videoEl.play(); 
    });

all same with demo code.

**Comment by mkay581** [comment]
what browser and version?

**Comment by winditprog** [comment]
hey, i use android chrome lastest version

**Comment by mkay581** [comment]
`.play()` can't be called manually on android devices (similar to other mobile browsers) unfortunately. So if the intention is to use this library on a mobile device, you'll need to remove the `.play()` (`.load()` is still fine) and allow the user to click the video to play it.

**Comment by mkay581** [comment]
[here](https://stackoverflow.com/questions/36799918/youtube-videos-using-latest-api-wont-play-on-chrome-on-android) is an article that talks a little about the limitations of .play() on mobile devices

**Comment by mkay581** [comment]
Closing issue for now. Let me know if you'd like to continue discussion
