### ISSUE TITLE
How to play video in full screen?

### ISSUE THREAD

**Issue by anilwarbhe** [mkay581/youtube-video-js#17]
I find no control except start, stop, pause etc. How can I make a video fullscreen?

**Comment by mkay581** [comment]
Hi! Thanks for filing issue. Unfortunately, the Youtube API doesn't allow us to trigger full screen using javascript. The only option is for the user to click the full screen icon while watching the video. Going to close this issue, but feel free to comment further if you would like to continue discussion.

**Comment by anilwarbhe** [comment]
But I do not see any icon on the video where user can click to make it a full screen.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mkay581** [comment]
Ah I see... I misunderstood your issue. I'm going to open a fix for this.

**Comment by mkay581** [comment]
The fix has been released in latest version [3.1.4](https://github.com/mkay581/youtube-video-js/releases/tag/v3.1.4). Let me know if you're having anymore problems. Thanks!

**Comment by anilwarbhe** [comment]
Dear Mark,

Thank you. I can see the icon to make a video full screen. And it is working as expected. But I am facing an issue. When I minimize the video from full screen it is not taking me to its original size.

Thanks.

www.ibizwaresolutions.com<http://www.ibizwaresolutions.com>
A Step to Hug the Universe!
"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will." - Vince Lombardi
________________________________

**Comment by mkay581** [comment]
@anilwarbhe this library just loads the youtube player. It doesn't control any minimizing that is done after full-screen mode. I've just verified that the youtube videos are minimizing after full screen for me. It may be your browser or the OS you're using. You'll have to file issues with either of them about it.
